name: Publish Packages

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (optional - will use package.json version if not specified)'
        required: false
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run type check
        run: npm run type-check

      - name: Run linting
        run: npm run lint

      - name: Build package
        run: npm run build

      - name: Update version if specified
        if: github.event.inputs.version
        run: npm version ${{ github.event.inputs.version }} --no-git-tag-version

      - name: Backup original files
        run: |
          cp package.json package.json.backup
          cp .npmrc .npmrc.backup

      - name: Publish to npm registry
        run: |
          # Configure for npm registry
          echo "registry=https://registry.npmjs.org/" > .npmrc
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
          
          # Remove scoped registry configuration for npm
          npm pkg delete publishConfig
          
          npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Restore files and configure for GitHub Packages
        run: |
          # Restore original files
          mv package.json.backup package.json
          mv .npmrc.backup .npmrc
          
          # Configure package for GitHub Packages
          npm pkg set name="@archivisio/c4-modelizer-sdk"
          npm pkg set publishConfig.registry="https://npm.pkg.github.com"
          npm pkg set publishConfig.access="restricted"
          npm pkg set repository.type="git"
          npm pkg set repository.url="git+https://github.com/archivisio/c4-modelizer-sdk.git"

      - name: Setup Node.js for GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@archivisio'

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore original files
        if: always()
        run: |
          if [ -f package.json.backup ]; then
            mv package.json.backup package.json
          fi
          if [ -f .npmrc.backup ]; then
            mv .npmrc.backup .npmrc
          fi

  test-install:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Test package installation
        run: |
          npm config set @archivisio:registry https://npm.pkg.github.com
          npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
          npm install @archivisio/c4-modelizer-sdk
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}