name: Publish to GitHub Packages

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (optional - will use package.json version if not specified)'
        required: false
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@eth3rnit3'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run type check
        run: npm run type-check

      - name: Run linting
        run: npm run lint

      - name: Build package
        run: npm run build

      - name: Update version if specified
        if: github.event.inputs.version
        run: npm version ${{ github.event.inputs.version }} --no-git-tag-version

      - name: Configure package for GitHub Packages
        run: |
          # Backup original package.json
          cp package.json package.json.backup
          
          # Update package name for GitHub Packages
          npm pkg set name="@eth3rnit3/c4-modelizer-sdk"
          
          # Add publishConfig for GitHub Packages
          npm pkg set publishConfig.registry="https://npm.pkg.github.com"
          npm pkg set publishConfig.access="restricted"
          
          # Add repository field if not present
          npm pkg set repository.type="git"
          npm pkg set repository.url="git+https://github.com/eth3rnit3/c4-modelizer-sdk.git"

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore original package.json
        if: always()
        run: mv package.json.backup package.json

  test-install:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Test package installation
        run: |
          npm config set @eth3rnit3:registry https://npm.pkg.github.com
          npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
          npm install @eth3rnit3/c4-modelizer-sdk
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}