name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Extract version from tag
        id: extract_version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: "Release v${{ steps.extract_version.outputs.version }}"
          body: |
            ## Changes in v${{ steps.extract_version.outputs.version }}
            
            🎉 New release of C4 Modelizer SDK
            
            ### Installation
            ```bash
            npm install @eth3rnit3/c4-modelizer-sdk@${{ steps.extract_version.outputs.version }}
            ```
            
            ### What's new
            - Auto-generated from tag v${{ steps.extract_version.outputs.version }}
            
            ### Full Changelog
            See [commits](https://github.com/${{ github.repository }}/commits/v${{ steps.extract_version.outputs.version }})
          draft: false
          prerelease: false